# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.srcs/sources_1/bd/SystolicCore/ip/SystolicCore_axi_fifo_mm_s_1_0/SystolicCore_axi_fifo_mm_s_1_0.xci
# IP: The module: 'SystolicCore_axi_fifo_mm_s_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.gen/sources_1/bd/SystolicCore/ip/SystolicCore_axi_fifo_mm_s_1_0/SystolicCore_axi_fifo_mm_s_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystolicCore_axi_fifo_mm_s_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.srcs/sources_1/bd/SystolicCore/ip/SystolicCore_axi_fifo_mm_s_1_0/SystolicCore_axi_fifo_mm_s_1_0.xci
# IP: The module: 'SystolicCore_axi_fifo_mm_s_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.gen/sources_1/bd/SystolicCore/ip/SystolicCore_axi_fifo_mm_s_1_0/SystolicCore_axi_fifo_mm_s_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystolicCore_axi_fifo_mm_s_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
