# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0/Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0.xci
# IP: The module: 'Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/ip/ila_1/ila_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] -quiet

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0/Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0.xci
# IP: The module: 'Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/ip/ila_1/ila_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] -quiet

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/ip/ila_0/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet
