# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SystolicCore_wrapper/SystolicCore_wrapper.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper || ORIG_REF_NAME==SystolicCore_wrapper} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_zynq_ultra_ps_e_0_0/SystolicCore_wrapper_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SystolicCore_wrapper_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_axi_smc_0/SystolicCore_wrapper_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_axi_smc_0 || ORIG_REF_NAME==SystolicCore_wrapper_axi_smc_0} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_rst_ps8_0_99M_0/SystolicCore_wrapper_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_rst_ps8_0_99M_0 || ORIG_REF_NAME==SystolicCore_wrapper_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_axi_fifo_mm_s_1_0/SystolicCore_wrapper_axi_fifo_mm_s_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==SystolicCore_wrapper_axi_fifo_mm_s_1_0} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_axi_fifo_mm_s_2_0/SystolicCore_wrapper_axi_fifo_mm_s_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_axi_fifo_mm_s_2_0 || ORIG_REF_NAME==SystolicCore_wrapper_axi_fifo_mm_s_2_0} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_AXI_Stream_Systolic_1_0/SystolicCore_wrapper_AXI_Stream_Systolic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_AXI_Stream_Systolic_1_0 || ORIG_REF_NAME==SystolicCore_wrapper_AXI_Stream_Systolic_1_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/ram_dual_port/ram_dual_port.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_dual_port || ORIG_REF_NAME==ram_dual_port} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_AXI_Stream_Systolic_2_0/SystolicCore_wrapper_AXI_Stream_Systolic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_AXI_Stream_Systolic_2_0 || ORIG_REF_NAME==SystolicCore_wrapper_AXI_Stream_Systolic_2_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/ram_dual_port/ram_dual_port.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_dual_port || ORIG_REF_NAME==ram_dual_port} -quiet] -quiet

# IP: bd/SystolicCore_wrapper/ip/SystolicCore_wrapper_onlyFPGA_0_0/SystolicCore_wrapper_onlyFPGA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_wrapper_onlyFPGA_0_0 || ORIG_REF_NAME==SystolicCore_wrapper_onlyFPGA_0_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/ram_dual_port/ram_dual_port.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_dual_port || ORIG_REF_NAME==ram_dual_port} -quiet] -quiet

# IP: ip/matrix_in_memeory/matrix_in_memeory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matrix_in_memeory || ORIG_REF_NAME==matrix_in_memeory} -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/SystolicCore_wrapper/SystolicCore_wrapper_ooc.xdc
