# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/teste_dma/teste_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma || ORIG_REF_NAME==teste_dma} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_zynq_ultra_ps_e_0_0/teste_dma_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==teste_dma_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_axi_dma_0_0/teste_dma_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_axi_dma_0_0 || ORIG_REF_NAME==teste_dma_axi_dma_0_0} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_axi_smc_0/teste_dma_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_axi_smc_0 || ORIG_REF_NAME==teste_dma_axi_smc_0} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_rst_ps8_0_99M_0/teste_dma_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_rst_ps8_0_99M_0 || ORIG_REF_NAME==teste_dma_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_axi_smc_1_0/teste_dma_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_axi_smc_1_0 || ORIG_REF_NAME==teste_dma_axi_smc_1_0} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_system_ila_0_0/teste_dma_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_system_ila_0_0 || ORIG_REF_NAME==teste_dma_system_ila_0_0} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_AXI_Stream_Systolic_0_0/teste_dma_AXI_Stream_Systolic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_AXI_Stream_Systolic_0_0 || ORIG_REF_NAME==teste_dma_AXI_Stream_Systolic_0_0} -quiet] -quiet

# IP: ip/ila_2/ila_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_2 || ORIG_REF_NAME==ila_2} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/ila_3/ila_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_3 || ORIG_REF_NAME==ila_3} -quiet] -quiet

# IP: bd/teste_dma/ip/teste_dma_axis_data_fifo_0_0/teste_dma_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==teste_dma_axis_data_fifo_0_0 || ORIG_REF_NAME==teste_dma_axis_data_fifo_0_0} -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/teste_dma_ooc.xdc
