# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.runs/synth_1/teste_dma_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_param general.usePosixSpawnForFork 1
set_param bd.open.in_stealth_mode 3
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.cache/wt [current_project]
set_property parent.project_path /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.6 [current_project]
set_property ip_output_repo /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/imports/SystolicCore/SystolicCore_Metricas/testeINPUT_A.coe
add_files /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/imports/SystolicCore/SystolicCore/testeINPUT_A.coe
read_verilog -library xil_defaultlib /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/hdl/teste_dma_wrapper.v
add_files /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/bd/teste_dma/teste_dma.bd
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_zynq_ultra_ps_e_0_0/teste_dma_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_zynq_ultra_ps_e_0_0/teste_dma_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_dma_0_0/teste_dma_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_dma_0_0/teste_dma_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_dma_0_0/teste_dma_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_1/bd_8f00_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_2/bd_8f00_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_3/bd_8f00_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_4/bd_8f00_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_5/bd_8f00_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_6/bd_8f00_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_7/bd_8f00_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_8/bd_8f00_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_9/bd_8f00_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_10/bd_8f00_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_11/bd_8f00_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_12/bd_8f00_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_13/bd_8f00_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_14/bd_8f00_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_15/bd_8f00_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_16/bd_8f00_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_20/bd_8f00_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_21/bd_8f00_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_22/bd_8f00_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_23/bd_8f00_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_24/bd_8f00_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_25/bd_8f00_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_29/bd_8f00_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_30/bd_8f00_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_31/bd_8f00_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_32/bd_8f00_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_33/bd_8f00_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_34/bd_8f00_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_35/bd_8f00_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_36/bd_8f00_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_37/bd_8f00_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_38/bd_8f00_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_39/bd_8f00_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_40/bd_8f00_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_rst_ps8_0_99M_0/teste_dma_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_rst_ps8_0_99M_0/teste_dma_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_1/bd_8029_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_2/bd_8029_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_3/bd_8029_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_4/bd_8029_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_5/bd_8029_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_6/bd_8029_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_10/bd_8029_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_11/bd_8029_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_12/bd_8029_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_16/bd_8029_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_17/bd_8029_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_18/bd_8029_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_19/bd_8029_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_20/bd_8029_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_21/bd_8029_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_22/bd_8029_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_23/bd_8029_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_24/bd_8029_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_25/bd_8029_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_1_0/smartconnect.xdc]
set_property used_in_synthesis false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/bd_2743_0_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/bd_2743_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/teste_dma_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_AXI_Stream_Systolic_0_0/teste_dma_AXI_Stream_Systolic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axis_data_fifo_0_0/teste_dma_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/teste_dma_ooc.xdc]

read_ip -quiet /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_2/ila_2.xci
set_property used_in_synthesis false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_2/ila_2_ooc.xdc]

read_ip -quiet /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_3/ila_3.xci
set_property used_in_synthesis false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/ip/ila_3/ila_3_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/utils_1/imports/synth_1/AXI_Stream_Systolic_Core.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top teste_dma_wrapper -part xczu7ev-ffvc1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef teste_dma_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file teste_dma_wrapper_utilization_synth.rpt -pb teste_dma_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
