# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/teste_dma_system_ila_0_0.xci
# IP: The module: 'teste_dma_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/bd_2743_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0 || ORIG_REF_NAME==bd_2743_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/bd_2743_0_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_ila_lib_0 || ORIG_REF_NAME==bd_2743_0_ila_lib_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_1/bd_2743_0_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_g_inst_0 || ORIG_REF_NAME==bd_2743_0_g_inst_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_2/bd_2743_0_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_0_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_3/bd_2743_0_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_w_0 || ORIG_REF_NAME==bd_2743_0_slot_0_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_4/bd_2743_0_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_b_0 || ORIG_REF_NAME==bd_2743_0_slot_0_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_5/bd_2743_0_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_0_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_6/bd_2743_0_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_r_0 || ORIG_REF_NAME==bd_2743_0_slot_0_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_7/bd_2743_0_slot_2_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_2_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_8/bd_2743_0_slot_2_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_w_0 || ORIG_REF_NAME==bd_2743_0_slot_2_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_9/bd_2743_0_slot_2_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_b_0 || ORIG_REF_NAME==bd_2743_0_slot_2_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_10/bd_2743_0_slot_2_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_2_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_11/bd_2743_0_slot_2_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_r_0 || ORIG_REF_NAME==bd_2743_0_slot_2_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_12/bd_2743_0_slot_3_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_3_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_13/bd_2743_0_slot_3_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_w_0 || ORIG_REF_NAME==bd_2743_0_slot_3_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_14/bd_2743_0_slot_3_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_b_0 || ORIG_REF_NAME==bd_2743_0_slot_3_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_15/bd_2743_0_slot_3_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_3_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_16/bd_2743_0_slot_3_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_r_0 || ORIG_REF_NAME==bd_2743_0_slot_3_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_17/bd_2743_0_slot_4_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_4_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_18/bd_2743_0_slot_4_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_w_0 || ORIG_REF_NAME==bd_2743_0_slot_4_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_19/bd_2743_0_slot_4_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_b_0 || ORIG_REF_NAME==bd_2743_0_slot_4_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_20/bd_2743_0_slot_4_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_4_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_21/bd_2743_0_slot_4_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_r_0 || ORIG_REF_NAME==bd_2743_0_slot_4_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_22/bd_2743_0_slot_5_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_5_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_23/bd_2743_0_slot_5_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_w_0 || ORIG_REF_NAME==bd_2743_0_slot_5_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_24/bd_2743_0_slot_5_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_b_0 || ORIG_REF_NAME==bd_2743_0_slot_5_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_25/bd_2743_0_slot_5_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_5_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_26/bd_2743_0_slot_5_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_r_0 || ORIG_REF_NAME==bd_2743_0_slot_5_r_0} -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2743_0_ila_lib_0 || ORIG_REF_NAME==bd_2743_0_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2743_0_ila_lib_0 || ORIG_REF_NAME==bd_2743_0_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/bd_2743_0_ila_lib_0_ooc.xdc

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/bd_2743_0_ooc.xdc

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/teste_dma_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_dma_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/teste_dma_system_ila_0_0.xci
# IP: The module: 'teste_dma_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/bd_2743_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0 || ORIG_REF_NAME==bd_2743_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/bd_2743_0_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_ila_lib_0 || ORIG_REF_NAME==bd_2743_0_ila_lib_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_1/bd_2743_0_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_g_inst_0 || ORIG_REF_NAME==bd_2743_0_g_inst_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_2/bd_2743_0_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_0_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_3/bd_2743_0_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_w_0 || ORIG_REF_NAME==bd_2743_0_slot_0_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_4/bd_2743_0_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_b_0 || ORIG_REF_NAME==bd_2743_0_slot_0_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_5/bd_2743_0_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_0_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_6/bd_2743_0_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_0_r_0 || ORIG_REF_NAME==bd_2743_0_slot_0_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_7/bd_2743_0_slot_2_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_2_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_8/bd_2743_0_slot_2_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_w_0 || ORIG_REF_NAME==bd_2743_0_slot_2_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_9/bd_2743_0_slot_2_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_b_0 || ORIG_REF_NAME==bd_2743_0_slot_2_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_10/bd_2743_0_slot_2_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_2_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_11/bd_2743_0_slot_2_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_2_r_0 || ORIG_REF_NAME==bd_2743_0_slot_2_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_12/bd_2743_0_slot_3_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_3_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_13/bd_2743_0_slot_3_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_w_0 || ORIG_REF_NAME==bd_2743_0_slot_3_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_14/bd_2743_0_slot_3_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_b_0 || ORIG_REF_NAME==bd_2743_0_slot_3_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_15/bd_2743_0_slot_3_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_3_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_16/bd_2743_0_slot_3_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_3_r_0 || ORIG_REF_NAME==bd_2743_0_slot_3_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_17/bd_2743_0_slot_4_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_4_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_18/bd_2743_0_slot_4_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_w_0 || ORIG_REF_NAME==bd_2743_0_slot_4_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_19/bd_2743_0_slot_4_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_b_0 || ORIG_REF_NAME==bd_2743_0_slot_4_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_20/bd_2743_0_slot_4_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_4_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_21/bd_2743_0_slot_4_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_4_r_0 || ORIG_REF_NAME==bd_2743_0_slot_4_r_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_22/bd_2743_0_slot_5_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_aw_0 || ORIG_REF_NAME==bd_2743_0_slot_5_aw_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_23/bd_2743_0_slot_5_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_w_0 || ORIG_REF_NAME==bd_2743_0_slot_5_w_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_24/bd_2743_0_slot_5_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_b_0 || ORIG_REF_NAME==bd_2743_0_slot_5_b_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_25/bd_2743_0_slot_5_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_ar_0 || ORIG_REF_NAME==bd_2743_0_slot_5_ar_0} -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_26/bd_2743_0_slot_5_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2743_0_slot_5_r_0 || ORIG_REF_NAME==bd_2743_0_slot_5_r_0} -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2743_0_ila_lib_0 || ORIG_REF_NAME==bd_2743_0_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2743_0_ila_lib_0 || ORIG_REF_NAME==bd_2743_0_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/bd_2743_0_ila_lib_0_ooc.xdc

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/bd_2743_0_ooc.xdc

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore_Metricas/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_system_ila_0_0/teste_dma_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_dma_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
