# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SystolicCore/SystolicCore.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore || ORIG_REF_NAME==SystolicCore} -quiet] -quiet

# IP: bd/SystolicCore/ip/SystolicCore_zynq_ultra_ps_e_0_1/SystolicCore_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==SystolicCore_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/SystolicCore/ip/SystolicCore_axi_fifo_mm_s_0_0/SystolicCore_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==SystolicCore_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/SystolicCore/ip/SystolicCore_axi_smc_0/SystolicCore_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_axi_smc_0 || ORIG_REF_NAME==SystolicCore_axi_smc_0} -quiet] -quiet

# IP: bd/SystolicCore/ip/SystolicCore_rst_ps8_0_99M_0/SystolicCore_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_rst_ps8_0_99M_0 || ORIG_REF_NAME==SystolicCore_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/SystolicCore/ip/SystolicCore_AXI_Stream_Systolic_0_0/SystolicCore_AXI_Stream_Systolic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_AXI_Stream_Systolic_0_0 || ORIG_REF_NAME==SystolicCore_AXI_Stream_Systolic_0_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/ila_1/ila_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] -quiet

# IP: ip/ram_dual_port/ram_dual_port.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_dual_port || ORIG_REF_NAME==ram_dual_port} -quiet] -quiet

# IP: bd/SystolicCore/ip/SystolicCore_system_ila_0_0/SystolicCore_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystolicCore_system_ila_0_0 || ORIG_REF_NAME==SystolicCore_system_ila_0_0} -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.gen/sources_1/bd/SystolicCore/SystolicCore_ooc.xdc
