# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/teste_dma_axi_smc_0.xci
# IP: The module: 'teste_dma_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/bd_8f00.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_1/bd_8f00_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_2/bd_8f00_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_3/bd_8f00_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_4/bd_8f00_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_5/bd_8f00_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_6/bd_8f00_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_7/bd_8f00_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_8/bd_8f00_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_9/bd_8f00_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_10/bd_8f00_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_11/bd_8f00_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_12/bd_8f00_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_13/bd_8f00_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_14/bd_8f00_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_15/bd_8f00_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_16/bd_8f00_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_17/bd_8f00_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_18/bd_8f00_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_19/bd_8f00_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_20/bd_8f00_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_21/bd_8f00_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_22/bd_8f00_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_23/bd_8f00_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_24/bd_8f00_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_25/bd_8f00_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_26/bd_8f00_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_27/bd_8f00_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_28/bd_8f00_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_29/bd_8f00_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_30/bd_8f00_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_31/bd_8f00_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_32/bd_8f00_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_33/bd_8f00_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_34/bd_8f00_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_35/bd_8f00_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_36/bd_8f00_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_37/bd_8f00_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_38/bd_8f00_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_39/bd_8f00_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_40/bd_8f00_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_41/bd_8f00_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_1/bd_8f00_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_2/bd_8f00_arinsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_3/bd_8f00_rinsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_4/bd_8f00_awinsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_5/bd_8f00_winsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_6/bd_8f00_binsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_7/bd_8f00_aroutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_8/bd_8f00_routsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_9/bd_8f00_awoutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_10/bd_8f00_woutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_11/bd_8f00_boutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_12/bd_8f00_arni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_13/bd_8f00_rni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_14/bd_8f00_awni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_15/bd_8f00_wni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_16/bd_8f00_bni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_20/bd_8f00_s00a2s_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_21/bd_8f00_sarn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_22/bd_8f00_srn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_23/bd_8f00_sawn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_24/bd_8f00_swn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_25/bd_8f00_sbn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_29/bd_8f00_s01a2s_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_30/bd_8f00_sarn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_31/bd_8f00_srn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_32/bd_8f00_sawn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_33/bd_8f00_swn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_34/bd_8f00_sbn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_35/bd_8f00_m00s2a_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_36/bd_8f00_m00arn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_37/bd_8f00_m00rn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_38/bd_8f00_m00awn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_39/bd_8f00_m00wn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_40/bd_8f00_m00bn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_dma_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_dma_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.srcs/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/teste_dma_axi_smc_0.xci
# IP: The module: 'teste_dma_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/bd_8f00.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_1/bd_8f00_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_2/bd_8f00_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_3/bd_8f00_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_4/bd_8f00_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_5/bd_8f00_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_6/bd_8f00_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_7/bd_8f00_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_8/bd_8f00_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_9/bd_8f00_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_10/bd_8f00_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_11/bd_8f00_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_12/bd_8f00_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_13/bd_8f00_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_14/bd_8f00_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_15/bd_8f00_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_16/bd_8f00_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_17/bd_8f00_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_18/bd_8f00_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_19/bd_8f00_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_20/bd_8f00_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_21/bd_8f00_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_22/bd_8f00_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_23/bd_8f00_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_24/bd_8f00_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_25/bd_8f00_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_26/bd_8f00_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_27/bd_8f00_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_28/bd_8f00_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_29/bd_8f00_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_30/bd_8f00_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_31/bd_8f00_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_32/bd_8f00_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_33/bd_8f00_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_34/bd_8f00_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_35/bd_8f00_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_36/bd_8f00_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_37/bd_8f00_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_38/bd_8f00_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_39/bd_8f00_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_40/bd_8f00_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_41/bd_8f00_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_1/bd_8f00_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_2/bd_8f00_arinsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_3/bd_8f00_rinsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_4/bd_8f00_awinsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_5/bd_8f00_winsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_6/bd_8f00_binsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_7/bd_8f00_aroutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_8/bd_8f00_routsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_9/bd_8f00_awoutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_10/bd_8f00_woutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_11/bd_8f00_boutsw_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_12/bd_8f00_arni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_13/bd_8f00_rni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_14/bd_8f00_awni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_15/bd_8f00_wni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_16/bd_8f00_bni_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_20/bd_8f00_s00a2s_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_21/bd_8f00_sarn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_22/bd_8f00_srn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_23/bd_8f00_sawn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_24/bd_8f00_swn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_25/bd_8f00_sbn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_29/bd_8f00_s01a2s_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_30/bd_8f00_sarn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_31/bd_8f00_srn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_32/bd_8f00_sawn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_33/bd_8f00_swn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_34/bd_8f00_sbn_1_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_35/bd_8f00_m00s2a_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_36/bd_8f00_m00arn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_37/bd_8f00_m00rn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_38/bd_8f00_m00awn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_39/bd_8f00_m00wn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_40/bd_8f00_m00bn_0_ooc.xdc

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_dma_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/valmyrsilva07/Área de Trabalho/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot/Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ip/teste_dma_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_dma_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
