transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/proc_sys_reset_v5_0_17
vlib riviera/xil_defaultlib
vlib riviera/smartconnect_v1_0
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_register_slice_v2_1_36
vlib riviera/axi_vip_v1_1_22
vlib riviera/gigantic_mux
vlib riviera/xlconcat_v2_1_7
vlib riviera/zynq_ultra_ps_e_vip_v1_0_22
vlib riviera/axi_datamover_v5_1_37
vlib riviera/axi_sg_v4_1_21
vlib riviera/axi_dma_v7_1_37
vlib riviera/axis_infrastructure_v1_1_1
vlib riviera/axis_data_fifo_v2_0_17

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap proc_sys_reset_v5_0_17 riviera/proc_sys_reset_v5_0_17
vmap xil_defaultlib riviera/xil_defaultlib
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_36 riviera/axi_register_slice_v2_1_36
vmap axi_vip_v1_1_22 riviera/axi_vip_v1_1_22
vmap gigantic_mux riviera/gigantic_mux
vmap xlconcat_v2_1_7 riviera/xlconcat_v2_1_7
vmap zynq_ultra_ps_e_vip_v1_0_22 riviera/zynq_ultra_ps_e_vip_v1_0_22
vmap axi_datamover_v5_1_37 riviera/axi_datamover_v5_1_37
vmap axi_sg_v4_1_21 riviera/axi_sg_v4_1_21
vmap axi_dma_v7_1_37 riviera/axi_dma_v7_1_37
vmap axis_infrastructure_v1_1_1 riviera/axis_infrastructure_v1_1_1
vmap axis_data_fifo_v2_0_17 riviera/axis_data_fifo_v2_0_17

vlog -work xilinx_vip  -incr "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work proc_sys_reset_v5_0_17 -93  -incr \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_1/sim/bd_0b88_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_2/sim/bd_0b88_arinsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_3/sim/bd_0b88_rinsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_4/sim/bd_0b88_awinsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_5/sim/bd_0b88_winsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_6/sim/bd_0b88_binsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_7/sim/bd_0b88_aroutsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_8/sim/bd_0b88_routsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_9/sim/bd_0b88_awoutsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_10/sim/bd_0b88_woutsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_11/sim/bd_0b88_boutsw_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_12/sim/bd_0b88_arni_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_13/sim/bd_0b88_rni_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_14/sim/bd_0b88_awni_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_15/sim/bd_0b88_wni_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_16/sim/bd_0b88_bni_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_17/sim/bd_0b88_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_18/sim/bd_0b88_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_19/sim/bd_0b88_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_20/sim/bd_0b88_s00a2s_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_21/sim/bd_0b88_sarn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_22/sim/bd_0b88_srn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_23/sim/bd_0b88_sawn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_24/sim/bd_0b88_swn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_25/sim/bd_0b88_sbn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_26/sim/bd_0b88_s01mmu_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_27/sim/bd_0b88_s01tr_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_28/sim/bd_0b88_s01sic_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_29/sim/bd_0b88_s01a2s_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_30/sim/bd_0b88_sarn_1.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_31/sim/bd_0b88_srn_1.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_32/sim/bd_0b88_sawn_1.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_33/sim/bd_0b88_swn_1.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_34/sim/bd_0b88_sbn_1.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_35/sim/bd_0b88_m00s2a_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_36/sim/bd_0b88_m00arn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_37/sim/bd_0b88_m00rn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_38/sim/bd_0b88_m00awn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_39/sim/bd_0b88_m00wn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_40/sim/bd_0b88_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/ip/ip_41/sim/bd_0b88_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/bd_0/sim/bd_0b88.v" \

vcom -work smartconnect_v1_0 -93  -incr \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_36  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/bc4b/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_22  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/b16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_0/sim/Systolic_DMA_AXI_Stream_axi_smc_0.sv" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_1/sim/bd_e34f_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_2/sim/bd_e34f_arsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_3/sim/bd_e34f_rsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_4/sim/bd_e34f_awsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_5/sim/bd_e34f_wsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_6/sim/bd_e34f_bsw_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_7/sim/bd_e34f_s00mmu_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_8/sim/bd_e34f_s00tr_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_9/sim/bd_e34f_s00sic_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_10/sim/bd_e34f_s00a2s_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_11/sim/bd_e34f_sarn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_12/sim/bd_e34f_srn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_13/sim/bd_e34f_s01mmu_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_14/sim/bd_e34f_s01tr_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_15/sim/bd_e34f_s01sic_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_16/sim/bd_e34f_s01a2s_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_17/sim/bd_e34f_sawn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_18/sim/bd_e34f_swn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_19/sim/bd_e34f_sbn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_20/sim/bd_e34f_m00s2a_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_21/sim/bd_e34f_m00arn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_22/sim/bd_e34f_m00rn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_23/sim/bd_e34f_m00awn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_24/sim/bd_e34f_m00wn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_25/sim/bd_e34f_m00bn_0.sv" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/ip/ip_26/sim/bd_e34f_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/bd_0/sim/bd_e34f.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_smc_1_0/sim/Systolic_DMA_AXI_Stream_axi_smc_1_0.sv" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_rst_ps8_0_99M_0/sim/Systolic_DMA_AXI_Stream_rst_ps8_0_99M_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_0/sim/bd_c88b_ila_lib_0.v" \

vlog -work gigantic_mux  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/b2b0/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_1/bd_c88b_g_inst_0_gigantic_mux.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_1/sim/bd_c88b_g_inst_0.v" \

vlog -work xlconcat_v2_1_7  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/9c1a/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_2/sim/bd_c88b_slot_3_aw_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_3/sim/bd_c88b_slot_3_w_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_4/sim/bd_c88b_slot_3_b_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_5/sim/bd_c88b_slot_3_ar_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/ip/ip_6/sim/bd_c88b_slot_3_r_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/bd_0/sim/bd_c88b.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_system_ila_0_0/sim/Systolic_DMA_AXI_Stream_system_ila_0_0.v" \

vlog -work zynq_ultra_ps_e_vip_v1_0_22  -incr "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_zynq_ultra_ps_e_0_0/sim/Systolic_DMA_AXI_Stream_zynq_ultra_ps_e_0_0_vip_wrapper.v" \

vcom -work axi_datamover_v5_1_37 -93  -incr \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_21 -93  -incr \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_37 -93  -incr \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/7f6a/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axi_dma_0_0/sim/Systolic_DMA_AXI_Stream_axi_dma_0_0.vhd" \

vlog -work axis_infrastructure_v1_1_1  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_17  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/e1e3/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/434f/hdl" "+incdir+../../../../../../../home/xmen/Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/bd/Systolic_DMA_AXI_Stream/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l gigantic_mux -l xlconcat_v2_1_7 -l zynq_ultra_ps_e_vip_v1_0_22 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_37 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_axis_data_fifo_0_0/sim/Systolic_DMA_AXI_Stream_axis_data_fifo_0_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_row_major_axi_convert_0_0/sim/Systolic_DMA_AXI_Stream_row_major_axi_convert_0_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/ip/Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0/sim/Systolic_DMA_AXI_Stream_AXI_Stream_Systolic_0_0.v" \
"../../../bd/Systolic_DMA_AXI_Stream/sim/Systolic_DMA_AXI_Stream.v" \

vlog -work xil_defaultlib \
"glbl.v"

