# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/xmen/ARTYA7/XilinxDesignConstraint/Arty-A7-100-Master.xdc

# IP: ip/ram_single_port/ram_single_port.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_single_port || ORIG_REF_NAME==ram_single_port} -quiet] -quiet
