vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xilinx_vip
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/axi_infrastructure_v1_1_0
vlib modelsim_lib/msim/axi_vip_v1_1_22
vlib modelsim_lib/msim/zynq_ultra_ps_e_vip_v1_0_22
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/axi_datamover_v5_1_37
vlib modelsim_lib/msim/axi_sg_v4_1_21
vlib modelsim_lib/msim/axi_dma_v7_1_37
vlib modelsim_lib/msim/proc_sys_reset_v5_0_17
vlib modelsim_lib/msim/smartconnect_v1_0
vlib modelsim_lib/msim/axi_register_slice_v2_1_36
vlib modelsim_lib/msim/gigantic_mux
vlib modelsim_lib/msim/xlconcat_v2_1_7
vlib modelsim_lib/msim/axis_infrastructure_v1_1_1
vlib modelsim_lib/msim/axis_data_fifo_v2_0_17

vmap xilinx_vip modelsim_lib/msim/xilinx_vip
vmap xpm modelsim_lib/msim/xpm
vmap axi_infrastructure_v1_1_0 modelsim_lib/msim/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_22 modelsim_lib/msim/axi_vip_v1_1_22
vmap zynq_ultra_ps_e_vip_v1_0_22 modelsim_lib/msim/zynq_ultra_ps_e_vip_v1_0_22
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap axi_datamover_v5_1_37 modelsim_lib/msim/axi_datamover_v5_1_37
vmap axi_sg_v4_1_21 modelsim_lib/msim/axi_sg_v4_1_21
vmap axi_dma_v7_1_37 modelsim_lib/msim/axi_dma_v7_1_37
vmap proc_sys_reset_v5_0_17 modelsim_lib/msim/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 modelsim_lib/msim/smartconnect_v1_0
vmap axi_register_slice_v2_1_36 modelsim_lib/msim/axi_register_slice_v2_1_36
vmap gigantic_mux modelsim_lib/msim/gigantic_mux
vmap xlconcat_v2_1_7 modelsim_lib/msim/xlconcat_v2_1_7
vmap axis_infrastructure_v1_1_1 modelsim_lib/msim/axis_infrastructure_v1_1_1
vmap axis_data_fifo_v2_0_17 modelsim_lib/msim/axis_data_fifo_v2_0_17

vlog -work xilinx_vip -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/xmen/Music/2025.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93  \
"/home/xmen/Music/2025.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_22 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/b16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work zynq_ultra_ps_e_vip_v1_0_22 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_zynq_ultra_ps_e_0_0/sim/teste_dma_zynq_ultra_ps_e_0_0_vip_wrapper.v" \

vcom -work axi_datamover_v5_1_37 -64 -93  \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_21 -64 -93  \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_37 -64 -93  \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/7f6a/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/teste_dma/ip/teste_dma_axi_dma_0_0/sim/teste_dma_axi_dma_0_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/sim/bd_8f00.v" \

vcom -work proc_sys_reset_v5_0_17 -64 -93  \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_1/sim/bd_8f00_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_2/sim/bd_8f00_arinsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_3/sim/bd_8f00_rinsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_4/sim/bd_8f00_awinsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_5/sim/bd_8f00_winsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_6/sim/bd_8f00_binsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_7/sim/bd_8f00_aroutsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_8/sim/bd_8f00_routsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_9/sim/bd_8f00_awoutsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_10/sim/bd_8f00_woutsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_11/sim/bd_8f00_boutsw_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_12/sim/bd_8f00_arni_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_13/sim/bd_8f00_rni_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_14/sim/bd_8f00_awni_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_15/sim/bd_8f00_wni_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_16/sim/bd_8f00_bni_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_17/sim/bd_8f00_s00mmu_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_18/sim/bd_8f00_s00tr_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_19/sim/bd_8f00_s00sic_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_20/sim/bd_8f00_s00a2s_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_21/sim/bd_8f00_sarn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_22/sim/bd_8f00_srn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_23/sim/bd_8f00_sawn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_24/sim/bd_8f00_swn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_25/sim/bd_8f00_sbn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_26/sim/bd_8f00_s01mmu_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_27/sim/bd_8f00_s01tr_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_28/sim/bd_8f00_s01sic_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_29/sim/bd_8f00_s01a2s_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_30/sim/bd_8f00_sarn_1.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_31/sim/bd_8f00_srn_1.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_32/sim/bd_8f00_sawn_1.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_33/sim/bd_8f00_swn_1.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_34/sim/bd_8f00_sbn_1.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_35/sim/bd_8f00_m00s2a_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_36/sim/bd_8f00_m00arn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_37/sim/bd_8f00_m00rn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_38/sim/bd_8f00_m00awn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_39/sim/bd_8f00_m00wn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_40/sim/bd_8f00_m00bn_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/bd_0/ip/ip_41/sim/bd_8f00_m00e_0.sv" \

vcom -work smartconnect_v1_0 -64 -93  \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.vhd" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.sv" \

vlog -work axi_register_slice_v2_1_36 -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/bc4b/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_0/sim/teste_dma_axi_smc_0.sv" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/teste_dma/ip/teste_dma_rst_ps8_0_99M_0/sim/teste_dma_rst_ps8_0_99M_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/sim/bd_8029.v" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_1/sim/bd_8029_psr_aclk_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L smartconnect_v1_0 -L axi_vip_v1_1_22 -L zynq_ultra_ps_e_vip_v1_0_22 -L xilinx_vip "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_2/sim/bd_8029_arsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_3/sim/bd_8029_rsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_4/sim/bd_8029_awsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_5/sim/bd_8029_wsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_6/sim/bd_8029_bsw_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_7/sim/bd_8029_s00mmu_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_8/sim/bd_8029_s00tr_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_9/sim/bd_8029_s00sic_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_10/sim/bd_8029_s00a2s_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_11/sim/bd_8029_sarn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_12/sim/bd_8029_srn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_13/sim/bd_8029_s01mmu_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_14/sim/bd_8029_s01tr_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_15/sim/bd_8029_s01sic_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_16/sim/bd_8029_s01a2s_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_17/sim/bd_8029_sawn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_18/sim/bd_8029_swn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_19/sim/bd_8029_sbn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_20/sim/bd_8029_m00s2a_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_21/sim/bd_8029_m00arn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_22/sim/bd_8029_m00rn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_23/sim/bd_8029_m00awn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_24/sim/bd_8029_m00wn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_25/sim/bd_8029_m00bn_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/bd_0/ip/ip_26/sim/bd_8029_m00e_0.sv" \
"../../../bd/teste_dma/ip/teste_dma_axi_smc_1_0/sim/teste_dma_axi_smc_1_0.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/sim/bd_2743_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_0/sim/bd_2743_0_ila_lib_0.v" \

vlog -work gigantic_mux -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/b2b0/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_1/bd_2743_0_g_inst_0_gigantic_mux.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_1/sim/bd_2743_0_g_inst_0.v" \

vlog -work xlconcat_v2_1_7 -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/9c1a/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_2/sim/bd_2743_0_slot_0_aw_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_3/sim/bd_2743_0_slot_0_w_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_4/sim/bd_2743_0_slot_0_b_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_5/sim/bd_2743_0_slot_0_ar_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_6/sim/bd_2743_0_slot_0_r_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_7/sim/bd_2743_0_slot_2_aw_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_8/sim/bd_2743_0_slot_2_w_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_9/sim/bd_2743_0_slot_2_b_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_10/sim/bd_2743_0_slot_2_ar_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_11/sim/bd_2743_0_slot_2_r_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_12/sim/bd_2743_0_slot_3_aw_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_13/sim/bd_2743_0_slot_3_w_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_14/sim/bd_2743_0_slot_3_b_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_15/sim/bd_2743_0_slot_3_ar_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_16/sim/bd_2743_0_slot_3_r_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_17/sim/bd_2743_0_slot_4_aw_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_18/sim/bd_2743_0_slot_4_w_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_19/sim/bd_2743_0_slot_4_b_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_20/sim/bd_2743_0_slot_4_ar_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_21/sim/bd_2743_0_slot_4_r_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_22/sim/bd_2743_0_slot_5_aw_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_23/sim/bd_2743_0_slot_5_w_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_24/sim/bd_2743_0_slot_5_b_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_25/sim/bd_2743_0_slot_5_ar_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/bd_1/ip/ip_26/sim/bd_2743_0_slot_5_r_0.v" \
"../../../bd/teste_dma/ip/teste_dma_system_ila_0_0/sim/teste_dma_system_ila_0_0.v" \
"../../../bd/teste_dma/ip/teste_dma_AXI_Stream_Systolic_0_0/sim/teste_dma_AXI_Stream_Systolic_0_0.v" \
"../../../bd/teste_dma/sim/teste_dma.v" \

vlog -work axis_infrastructure_v1_1_1 -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_17 -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/e1e3/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/ec67/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/a0fe/hdl" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/f0b6/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/00fe/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/434f/hdl" "+incdir+../../../../../../../../../Music/2025.2/data/rsb/busdef" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/5431/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/4e08/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/0568/hdl/verilog" "+incdir+../../../../Zynq_Systolic_Core_AXI_FIFO_Stream_Reboot.gen/sources_1/bd/teste_dma/ipshared/3556/hdl/verilog" "+incdir+/home/xmen/Music/2025.2/data/xilinx_vip/include" \
"../../../bd/teste_dma/ip/teste_dma_axis_data_fifo_0_0/sim/teste_dma_axis_data_fifo_0_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

