#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Nov 08 12:14:56 -03 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Arty7_top_sim_time_synth -key {Post-Synthesis:sim_1:Timing:Arty7_top_sim} -tclbatch Arty7_top_sim.tcl -view /home/xmen/Desktop/compara/analise/SystolicMatrixMultiplication/project_1/tb_behav.wcfg -view /home/xmen/Desktop/compara/analise/SystolicMatrixMultiplication/project_1/tb_behav1.wcfg -log simulate.log"
xsim Arty7_top_sim_time_synth -key {Post-Synthesis:sim_1:Timing:Arty7_top_sim} -tclbatch Arty7_top_sim.tcl -view /home/xmen/Desktop/compara/analise/SystolicMatrixMultiplication/project_1/tb_behav.wcfg -view /home/xmen/Desktop/compara/analise/SystolicMatrixMultiplication/project_1/tb_behav1.wcfg -log simulate.log

