# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.srcs/sources_1/ip/ila_4/ila_4.xci
# IP: The module: 'ila_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.gen/sources_1/ip/ila_4/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.gen/sources_1/ip/ila_4/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.gen/sources_1/ip/ila_4/ila_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.srcs/sources_1/ip/ila_4/ila_4.xci
# IP: The module: 'ila_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.gen/sources_1/ip/ila_4/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.gen/sources_1/ip/ila_4/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/SystolicCore/SystolicCore.gen/sources_1/ip/ila_4/ila_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
