# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.srcs/sources_1/bd/SystolicCore/ip/SystolicCore_AXI_Stream_Systolic_1_0/SystolicCore_AXI_Stream_Systolic_1_0.xci
# IP: The module: 'SystolicCore_AXI_Stream_Systolic_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.srcs/sources_1/ip/ila_4/ila_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_4 || ORIG_REF_NAME==ila_4} -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.gen/sources_1/bd/SystolicCore/ip/SystolicCore_AXI_Stream_Systolic_1_0/SystolicCore_AXI_Stream_Systolic_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystolicCore_AXI_Stream_Systolic_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.srcs/sources_1/bd/SystolicCore/ip/SystolicCore_AXI_Stream_Systolic_1_0/SystolicCore_AXI_Stream_Systolic_1_0.xci
# IP: The module: 'SystolicCore_AXI_Stream_Systolic_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.srcs/sources_1/ip/ila_4/ila_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_4 || ORIG_REF_NAME==ila_4} -quiet] -quiet

# XDC: /home/xmen/Videos/RustDesk/SystolicCore/SystolicCore/Zynq_Systolic_Core_AXI_FIFO_Stream/Zynq_Systolic_Core_AXI_FIFO_Stream.gen/sources_1/bd/SystolicCore/ip/SystolicCore_AXI_Stream_Systolic_1_0/SystolicCore_AXI_Stream_Systolic_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystolicCore_AXI_Stream_Systolic_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
