#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 25 11:55:58 -03 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -protoinst "protoinst_files/bd_ae77.protoinst" -protoinst "protoinst_files/bd_8f00.protoinst" -protoinst "protoinst_files/bd_8029.protoinst" -protoinst "protoinst_files/bd_2743_0.protoinst" -protoinst "protoinst_files/teste_dma.protoinst" -log simulate.log"
xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -protoinst "protoinst_files/bd_ae77.protoinst" -protoinst "protoinst_files/bd_8f00.protoinst" -protoinst "protoinst_files/bd_8029.protoinst" -protoinst "protoinst_files/bd_2743_0.protoinst" -protoinst "protoinst_files/teste_dma.protoinst" -log simulate.log

