# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/ip/matrix_in_memeory/matrix_in_memeory.xci
# IP: The module: 'matrix_in_memeory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/ip/matrix_in_memeory/matrix_in_memeory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_in_memeory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.srcs/sources_1/ip/matrix_in_memeory/matrix_in_memeory.xci
# IP: The module: 'matrix_in_memeory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /TCC/SystolicCore_Metricas/Zynq_Systolic_AXI_FIFO_DMA_Vitis_TEST/Zynq_Systolic_AXI_FIFO_DMA.gen/sources_1/ip/matrix_in_memeory/matrix_in_memeory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_in_memeory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
