set_property SRC_FILE_INFO {cfile:/home/xmen/Desktop/compara/analise/SystolicMatrixMultiplication/project_1/project_1.srcs/constrs_1/imports/XilinxDesignConstraint/Arty-A7-100-Master.xdc rfile:../../../project_1.srcs/constrs_1/imports/XilinxDesignConstraint/Arty-A7-100-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clock]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports {btn[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports uart_rxd_out]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports uart_txd_in]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btn_IBUF[0]]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_operating_conditions -process maximum
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_systlcCntrlUnt_Glbl
add_cells_to_pblock [get_pblocks pblock_systlcCntrlUnt_Glbl] [get_cells -quiet [list systolicControlUnit_Global]]
