domain_path: /home/xmen/Desktop/ZynqIOEthernet/ZyqnIO_EThernet/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/xmen/Music/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
